# Generated by Django 4.0.4 on 2023-04-17 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_remove_evento_criador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
