# Generated by Django 4.0.4 on 2023-04-18 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
